Repository dm-plz/family-farm-main-server, pull requests merged in 2024-08, with the labels that each got.

#6 에러핸들러 구현 기능 추가
  .gitignore
  build.gradle
  src/main/java/DM_plz/family_farm_main_server/common/exception/ErrorResponse.java
  src/main/java/DM_plz/family_farm_main_server/common/exception/errorCode/CommonErrorCode.java
  src/main/java/DM_plz/family_farm_main_server/common/exception/errorCode/ErrorCode.java
  src/main/java/DM_plz/family_farm_main_server/common/exception/exception/CommonException.java
  src/main/java/DM_plz/family_farm_main_server/common/exception/handler/GlobalExceptionHandler.java
  src/test/java/DM_plz/family_farm_main_server/common/exception/handler/GlobalExceptionHandlerTest.java
Labels: 기능 추가, 리펙토링, 테스트

#9 H2 데이터베이스 속성 설정, SecurityConfig 설정
  .gitignore
  src/main/java/DM_plz/family_farm_main_server/config/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 기능 추가

#11 refactor: requestMatchers 허용 경로 줄바꿈 적용
  src/main/java/DM_plz/family_farm_main_server/config/SecurityConfig.java
Labels: 리펙토링

#13 엔티티 생성
  src/main/java/DM_plz/family_farm_main_server/family/domain/Family.java
  src/main/java/DM_plz/family_farm_main_server/family/domain/InviteCode.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/Account.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/AuthProvider.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/BirthType.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/MemberInfo.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/SurveyNumber.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/AllowedAnswerType.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/Answer.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/AnswerType.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/Comment.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/Question.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/QuestionHistory.java
  src/main/java/DM_plz/family_farm_main_server/survey/domain/SurveyAnswer.java
  src/main/java/DM_plz/family_farm_main_server/survey/domain/SurveyQuestion.java
Labels: 기능 추가, 정리

#15 MemberInfo 엔티티 이름 변경 및 유저 관련 엔티티 DAO 긴급 업로드
  src/main/java/DM_plz/family_farm_main_server/family/domain/Family.java
  src/main/java/DM_plz/family_farm_main_server/member/application/MemberService.java
  src/main/java/DM_plz/family_farm_main_server/member/dao/AccountRepository.java
  src/main/java/DM_plz/family_farm_main_server/member/dao/MemberDetailRepository.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/Account.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/GroupRole.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/MemberDetail.java
  src/main/java/DM_plz/family_farm_main_server/member/dto/SignUpDTO.java
  src/main/java/DM_plz/family_farm_main_server/member/dto/SignUpMapper.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/Answer.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/Comment.java
  src/main/java/DM_plz/family_farm_main_server/survey/domain/SurveyAnswer.java
Labels: 기능 추가, 긴급, 정리

#16 DAO의 반환 형태 Optional로 감싸기
  src/main/java/DM_plz/family_farm_main_server/member/dao/AccountRepository.java
Labels: 긴급, 버그 수정

#18 회원 service 기능 추가, ERD 수정사항 반영, Query logging 설정 추가
  .gitignore
  build.gradle
  src/main/java/DM_plz/family_farm_main_server/family/dao/FamilyRepository.java
  src/main/java/DM_plz/family_farm_main_server/family/domain/Family.java
  src/main/java/DM_plz/family_farm_main_server/family/domain/InviteCode.java
  src/main/java/DM_plz/family_farm_main_server/member/application/MemberService.java
  src/main/java/DM_plz/family_farm_main_server/member/dao/AccountRepository.java
  src/main/java/DM_plz/family_farm_main_server/member/dao/MemberDetailRepository.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/Member.java
  src/main/java/DM_plz/family_farm_main_server/member/domain/MemberDetail.java
  src/main/java/DM_plz/family_farm_main_server/member/dto/SignUpDTO.java
  src/main/java/DM_plz/family_farm_main_server/member/dto/SignUpMapper.java
  src/main/resources/application.yml
  src/test/java/DM_plz/family_farm_main_server/member/application/MemberServiceTest.java
Labels: 기능 추가, 리펙토링, 빌드, 정리

#21 가족코드 유효성 검사 기능
  src/main/java/DM_plz/family_farm_main_server/auth/api/AuthController.java
  src/main/java/DM_plz/family_farm_main_server/auth/application/AuthService.java
  src/main/java/DM_plz/family_farm_main_server/auth/dto/ValidateFamilyCode.java
  src/main/java/DM_plz/family_farm_main_server/family/application/FamilyService.java
  src/main/java/DM_plz/family_farm_main_server/member/application/MemberService.java
  src/main/java/DM_plz/family_farm_main_server/member/dao/MemberDetailRepository.java
  src/main/java/DM_plz/family_farm_main_server/member/dao/MemberRepository.java
  src/test/java/DM_plz/family_farm_main_server/auth/application/AuthServiceTest.java
  src/test/java/DM_plz/family_farm_main_server/member/application/MemberServiceTest.java
Labels: 기능 추가, 버그 수정

#24 fix: quesstion과 question_history 테이블 연관관계 적용
  src/main/java/DM_plz/family_farm_main_server/qna/domain/Question.java
  src/main/java/DM_plz/family_farm_main_server/qna/domain/QuestionHistory.java
Labels: 긴급, 버그 수정

#26 현재 진행중인 질문이 노출되는 기능(Q-1) API 구현
  src/main/java/DM_plz/family_farm_main_server/family/dao/FamilyRepository.java
  src/main/java/DM_plz/family_farm_main_server/family/domain/Family.java
  src/main/java/DM_plz/family_farm_main_server/member/application/MemberService.java
  src/main/java/DM_plz/family_farm_main_server/member/dto/SignUpMapper.java
  src/main/java/DM_plz/family_farm_main_server/qna/api/QnaController.java
  src/main/java/DM_plz/family_farm_main_server/qna/application/QuestionService.java
  src/main/java/DM_plz/family_farm_main_server/qna/dao/QuestionHistoryRepository.java
  src/main/java/DM_plz/family_farm_main_server/qna/dao/QuestionRepository.java
  src/main/java/DM_plz/family_farm_main_server/qna/dto/CurrentQuestion.java
  src/main/java/DM_plz/family_farm_main_server/qna/dto/CurrentQuestionMapper.java
  src/test/java/DM_plz/family_farm_main_server/qna/application/QuestionServiceTest.java
Labels: 기능 추가, 리펙토링

#29 가족코드 발급 및 재발급 기능 API(F-1, F-2)
  src/main/java/DM_plz/family_farm_main_server/common/exception/errorCode/FamilyErrorCode.java
  src/main/java/DM_plz/family_farm_main_server/common/exception/exception/FamilyException.java
  src/main/java/DM_plz/family_farm_main_server/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/DM_plz/family_farm_main_server/family/api/FamilyController.java
  src/main/java/DM_plz/family_farm_main_server/family/application/FamilyService.java
  src/main/java/DM_plz/family_farm_main_server/family/domain/Family.java
  src/main/java/DM_plz/family_farm_main_server/family/dto/FamilyCode.java
  src/main/java/DM_plz/family_farm_main_server/family/dto/FamilyCodeMapper.java
  src/test/java/DM_plz/family_farm_main_server/family/application/FamilyServiceTest.java
Labels: 기능 추가

#35 ci, build: gradle 파일 추가
  .DS_Store
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: 긴급, 빌드

#36 설문조사 노출 및 제출 기능(S-1, S-2)
  src/main/java/DM_plz/family_farm_main_server/member/dao/MemberDetailRepository.java
  src/main/java/DM_plz/family_farm_main_server/survey/api/SurveyController.java
  src/main/java/DM_plz/family_farm_main_server/survey/application/SurveyService.java
  src/main/java/DM_plz/family_farm_main_server/survey/dao/SurveyAnswerRepository.java
  src/main/java/DM_plz/family_farm_main_server/survey/dao/SurveyQuestionRepository.java
  src/main/java/DM_plz/family_farm_main_server/survey/domain/SurveyAnswer.java
  src/main/java/DM_plz/family_farm_main_server/survey/dto/SurveyAnswerList.java
  src/main/java/DM_plz/family_farm_main_server/survey/dto/SurveyMapper.java
  src/main/java/DM_plz/family_farm_main_server/survey/dto/SurveyQuestionList.java
  src/main/resources/application.yml
  src/test/java/DM_plz/family_farm_main_server/survey/application/SurveyServiceTest.java
Labels: 기능 추가
